### ISSUE TITLE
Dependency on base is not strict enough

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc#46]
Building with base 4.6 fails:
<pre>
[138 of 259] Compiling UHC.Compiler.CoreRun.Run.Val.Prim ( UHC/Compiler/CoreRun/Run/Val/Prim.hs, dist/build/UHC/Compiler/CoreRun/Run/Val/Prim.o )

src/ehc/CoreRun/Run/Val/Prim.chs:90:111:
    Not in scope: `bitSizeMaybe'

src/ehc/CoreRun/Run/Val/Prim.chs:91:93:
    Not in scope: `bitSizeMaybe'
</pre>

bitSizeMaybe is not available before base 4.7. Problem is introduced by commit ea6b75a.

I don't see an easy work-around to get it working with base 4.6 . But at least the dependency in configure.ac should be updated. I can't fix and test it myself, as I am still using ghc 7.6/base4.6.

(Btw, is there a configure flag to disable CoreRun? I couldn't find one.)

**Comment by atzedijkstra** [comment]
I'll change the use of bitSizeMaybe to bitSize, which then will complain about being deprecated with GHC7.8 but it won't break stuff at least. When 7.10 arrives most ghc users will probably have switched to 7.8 already. Maintaining backwards compatibility will be a problem/challenge/impossibility anyway with the major changes taking place with new/expected GHC/library versions.

There is no cabal file configure flag for disabling CoreRun, all configuration is done when building the package, cabal file is generated on the fly. For now I'd prefer to avoid the added complication of another layer of configuration.

Atze


> On  27 Feb, 2015, at 12:15 , Philipp Hausmann <notifications@github.com> wrote:
> 
> Building with base 4.6 fails:
> 
> [138 of 259] Compiling UHC.Compiler.CoreRun.Run.Val.Prim ( UHC/Compiler/CoreRun/Run/Val/Prim.hs, dist/build/UHC/Compiler/CoreRun/Run/Val/Prim.o )
> 
> src/ehc/CoreRun/Run/Val/Prim.chs:90:111:
>     Not in scope: `bitSizeMaybe'
> 
> src/ehc/CoreRun/Run/Val/Prim.chs:91:93:
>     Not in scope: `bitSizeMaybe'
> 
> bitSizeMaybe is not available before base 4.7. Problem is introduced by commit ea6b75a.
> 
> I don't see an easy work-around to get it working with base 4.6 . But at least the dependency in configure.ac should be updated. I can't fix and test it myself, as I am still using ghc 7.6/base4.6.
> 
> (Btw, is there a configure flag to disable CoreRun? I couldn't find one.)
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by phile314** [comment]
I think this is fixed by commit c278290fc59f24d54ab919128c106350ea0022cb.
